# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: upload
    runs-on: ubuntu-latest

    steps:
    - run: npm i
    - name: Build project
      id: build
      shell: bash
      run: |
        tar cvfz backend.tar.gz backend/*